// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvvYpLnCMpmTuaNXB1i0ZqgG08mmOF9cA',
    appId: '1:884652869655:web:f61abcaae93b186305b452',
    messagingSenderId: '884652869655',
    projectId: 'expense-tracker-2e931',
    authDomain: 'expense-tracker-2e931.firebaseapp.com',
    storageBucket: 'expense-tracker-2e931.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiREnCYu_we1_LNw07rVUwc5U9qGybPNM',
    appId: '1:884652869655:android:907081ca285d725605b452',
    messagingSenderId: '884652869655',
    projectId: 'expense-tracker-2e931',
    storageBucket: 'expense-tracker-2e931.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCBmOA5jq8auzywe71LRuDtt4-6zTirY',
    appId: '1:884652869655:ios:fbe091dffcd9a7aa05b452',
    messagingSenderId: '884652869655',
    projectId: 'expense-tracker-2e931',
    storageBucket: 'expense-tracker-2e931.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCBmOA5jq8auzywe71LRuDtt4-6zTirY',
    appId: '1:884652869655:ios:188aeb865263877c05b452',
    messagingSenderId: '884652869655',
    projectId: 'expense-tracker-2e931',
    storageBucket: 'expense-tracker-2e931.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
